import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { AppointmentCard } from "@/dashboard/AppointmentCard";
import { CalendarAssistant } from "@/dashboard/CalendarAssistant";
import {
  IconFilter,
  IconStatCompleted,
  IconStatPatients,
  IconStatPending,
} from "@/dashboard/DashboardIcons";
import { PatientNoteCard } from "@/dashboard/PatientNoteCard";
import { StatCard } from "@/dashboard/StatCard";
import { AppShell } from "@/components/layout/AppShell";
import { StateMessage } from "@/components/StateMessage";
import { api, responseData } from "@/services/api";
import type {
  Appointment,
  AssistantMessage,
  PatientNote,
  StatCardData,
} from "@/dashboard/types";

/** Dashboard preview: show at most this many appointment cards so the calendar assistant keeps room. */
const DASHBOARD_APPOINTMENT_PREVIEW = 2;

const DASHBOARD_CALENDAR_WELCOME: AssistantMessage[] = [
  {
    id: "welcome",
    role: "assistant",
    text: 'Schedule or change visits in plain language — e.g. "What\'s tomorrow?" or "Schedule Jane Doe for follow-up Monday at 2pm". Types: follow-up, new visit, lab review, annual physical, consultation.',
  },
];

function initials(name = "") {
  return name
    .split(" ")
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0])
    .join("")
    .toUpperCase();
}

function formatTime(time = "") {
  if (!time) return "";
  const [hour, minute] = time.split(":").map(Number);
  const date = new Date();
  date.setHours(hour, minute || 0, 0, 0);
  return date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
}

function timeAgo(date: string) {
  const minutes = Math.max(1, Math.floor((Date.now() - new Date(date).getTime()) / 60000));
  if (minutes < 60) return `${minutes} MIN AGO`;
  return `${Math.floor(minutes / 60)} HOURS AGO`;
}

type NoteSortOrder = "new-old" | "old-new";

export default function Dashboard() {
  const [appointments, setAppointments] = useState<Appointment[]>([]);
  const [notes, setNotes] = useState<PatientNote[]>([]);
  const [noteSortOrder, setNoteSortOrder] = useState<NoteSortOrder>("new-old");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  async function loadDashboard() {
    setLoading(true);
    setError("");
    try {
      const summaryResponse = await api.get("/dashboard/summary");
      const summary = responseData<{
        appointments: any[];
        notes: any[];
      }>(summaryResponse);

      setAppointments(
        (summary.appointments || []).map((appointment) => ({
          initials: initials(appointment.patientId?.name),
          avatarBg: "bg-[rgba(30, 42, 56,0.10)]",
          initialsColor: "text-[#1E2A38]",
          name: appointment.patientId?.name || "Unknown Patient",
          time: formatTime(appointment.time),
          visit: appointment.type,
          status: appointment.status,
        })),
      );

      setNotes(
        (summary.notes || []).map((note) => {
          const createdRaw = note.createdAt;
          const createdAt =
            createdRaw != null ? String(createdRaw) : new Date(0).toISOString();
          return {
            noteId: note._id ? String(note._id) : undefined,
            createdAt,
            patient: note.patientId?.name || "Unknown Patient",
            visitType: note.appointmentId?.type || "Clinical Note",
            timeAgo: timeAgo(createdAt),
            excerpt:
              note.soapNote?.assessment ||
              note.soapNote?.subjective ||
              "Clinical note generated by MedFlow.",
            tags: note.tags?.length ? note.tags : ["#Visit"],
          };
        }),
      );
    } catch {
      setAppointments([]);
      setNotes([]);
      setError("We could not load today’s MedFlow dashboard data.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void loadDashboard();
  }, []);

  const displayedNotes = useMemo(() => {
    const sorted = [...notes].sort((a, b) => {
      const ta = new Date(a.createdAt ?? 0).getTime();
      const tb = new Date(b.createdAt ?? 0).getTime();
      return noteSortOrder === "new-old" ? tb - ta : ta - tb;
    });
    const top = sorted.slice(0, 4);
    return top.map((note, index) => ({
      ...note,
      highlighted:
        noteSortOrder === "new-old" ? index === 0 : index === top.length - 1,
    }));
  }, [notes, noteSortOrder]);

  const stats: StatCardData[] = useMemo(
    () => [
      {
        iconBg: "bg-[rgba(30, 42, 56,0.12)]",
        icon: <IconStatPatients />,
        label: "TOTAL PATIENTS TODAY",
        value: appointments.length,
      },
      {
        iconBg: "bg-[rgba(30, 42, 56,0.20)]",
        icon: <IconStatCompleted />,
        label: "COMPLETED VISITS",
        value: appointments.filter((appointment) => appointment.status === "completed").length,
      },
      {
        iconBg: "bg-[rgba(30, 42, 56,0.10)]",
        icon: <IconStatPending />,
        label: "PENDING NOTES",
        value: appointments.filter((appointment) => appointment.status !== "completed").length,
      },
    ],
    [appointments],
  );

  return (
    <AppShell>
      <div className="flex min-h-0 flex-1 flex-col overflow-hidden px-5 pt-1 pb-2 md:px-6 md:pb-3 xl:px-8 xl:pb-4">
        <header className="mb-3 shrink-0">
          <h1 className="text-[#1A1A2E] text-2xl md:text-[30px] font-bold">Dashboard</h1>
          <p className="text-[#6B7280] mt-0.5 text-sm md:text-base leading-snug">
            Today&apos;s visits, notes, and calendar tools at a glance.
          </p>
        </header>
        {loading && (
          <div className="flex min-h-0 flex-1 items-center justify-center py-8">
            <StateMessage
              tone="loading"
              title="Loading dashboard"
              message="Fetching appointments, notes, and visit stats."
            />
          </div>
        )}
        {error && !loading && (
          <div className="flex min-h-0 flex-1 items-center justify-center py-8">
            <StateMessage
              tone="error"
              title="Dashboard unavailable"
              message={error}
              actionLabel="Retry"
              onAction={() => void loadDashboard()}
            />
          </div>
        )}
        {!loading && !error && (
          <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-hidden lg:gap-5">
            <div className="grid shrink-0 grid-cols-1 gap-3 sm:grid-cols-3 sm:gap-4 lg:gap-5">
              {stats.map((stat) => (
                <StatCard key={stat.label} {...stat} />
              ))}
            </div>

            <div className="flex min-h-0 flex-1 flex-col gap-6 overflow-hidden xl:flex-row xl:items-stretch xl:gap-8">
              <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-hidden xl:h-full xl:min-w-0">
                <section className="flex shrink-0 flex-col">
                  <div className="mb-2 flex items-center justify-between gap-3">
                    <h2 className="text-[#161D19] text-[18px] font-semibold leading-7 tracking-[-0.2px] sm:text-[20px]">
                      Today&apos;s Appointments
                    </h2>
                    <Link
                      to="/appointments"
                      className="shrink-0 text-[#1E2A38] text-sm font-medium leading-6 hover:underline sm:text-[15px]"
                    >
                      View all appointments
                    </Link>
                  </div>
                  <div className="flex flex-col gap-2">
                    {appointments.slice(0, DASHBOARD_APPOINTMENT_PREVIEW).map((appointment, index) => (
                      <AppointmentCard
                        key={`${appointment.name}-${appointment.time}-${index}`}
                        {...appointment}
                      />
                    ))}
                    {appointments.length > DASHBOARD_APPOINTMENT_PREVIEW && (
                      <p className="text-center text-xs text-[#6B7280] pt-0.5 sm:text-sm">
                        +{appointments.length - DASHBOARD_APPOINTMENT_PREVIEW} more —{" "}
                        <Link
                          to="/appointments"
                          className="font-medium text-[#1E2A38] hover:underline"
                        >
                          view all
                        </Link>
                      </p>
                    )}
                    {!appointments.length && (
                      <StateMessage
                        title="No appointments today"
                        message="Scheduled visits for today will appear here."
                      />
                    )}
                  </div>
                </section>

                <section className="flex min-h-0 flex-1 flex-col gap-2">
                  <h2 className="shrink-0 text-[#161D19] text-[18px] font-semibold leading-7 tracking-[-0.2px] sm:text-[20px]">
                    Calendar Assistant
                  </h2>
                  <div className="flex flex-1 flex-col overflow-hidden min-h-[300px] sm:min-h-[340px] lg:min-h-[360px]">
                    <CalendarAssistant
                      layout="fill"
                      variant="dashboard"
                      messages={DASHBOARD_CALENDAR_WELCOME}
                      onSuccess={() => void loadDashboard()}
                    />
                  </div>
                </section>
              </div>

              <aside className="flex min-h-0 flex-1 flex-col overflow-hidden border-t border-[#E5E7EB] pt-6 xl:h-full xl:w-[420px] xl:max-w-[440px] xl:flex-none xl:border-t-0 xl:pt-0">
                <div className="mb-2 flex shrink-0 flex-wrap items-center justify-between gap-2">
                  <h2 className="text-[#161D19] text-[18px] font-semibold leading-7 tracking-[-0.2px] sm:text-[20px]">
                    Recent Patient Notes
                  </h2>
                  <label className="flex items-center gap-2 text-sm text-[#3C4A42]">
                    <span className="hidden sm:inline">Sort</span>
                    <span className="inline-flex text-[#3C4A42]" aria-hidden>
                      <IconFilter />
                    </span>
                    <select
                      value={noteSortOrder}
                      onChange={(event) =>
                        setNoteSortOrder(event.target.value as NoteSortOrder)
                      }
                      className="max-w-[200px] rounded-lg border border-[#E5E7EB] bg-white px-3 py-1.5 text-[13px] font-medium text-[#161D19] outline-none focus:border-[#1E2A38] focus:ring-1 focus:ring-[#1E2A38]/25"
                      aria-label="Sort notes by date"
                    >
                      <option value="new-old">Newest → oldest</option>
                      <option value="old-new">Oldest → newest</option>
                    </select>
                  </label>
                </div>

                <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-[#E5E7EB] bg-white shadow-sm">
                  <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain">
                    {displayedNotes.map((note, i) => {
                      const { createdAt: _createdAt, ...card } = note;
                      return (
                        <PatientNoteCard
                          key={note.noteId ?? `${note.createdAt ?? ""}-${note.patient}-${i}`}
                          {...card}
                          hasDivider={i > 0}
                        />
                      );
                    })}
                    {!displayedNotes.length && (
                      <div className="flex min-h-[120px] flex-col justify-center p-4">
                        <StateMessage
                          title="No notes yet"
                          message="Recent AI-generated visit summaries will appear here."
                        />
                      </div>
                    )}
                  </div>
                </div>

                <Link
                  to="/notes"
                  className="mt-4 h-[52px] w-full shrink-0 rounded-lg text-[17px] font-bold leading-6 transition-colors medflow-primary-button sm:h-[54px] sm:text-[19px]"
                >
                  <span className="flex h-full items-center justify-center">View All Notes</span>
                </Link>
              </aside>
            </div>
          </div>
        )}
      </div>
    </AppShell>
  );
}
